# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('lteband', models.FloatField()),
                ('ltebw', models.FloatField()),
                ('rxchan', models.FloatField()),
                ('txchan', models.FloatField()),
                ('emmstate', models.CharField(max_length=200)),
                ('rccstate', models.CharField(max_length=200)),
                ('imsstate', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
